spring:
  config:
    import: optional:file:.env.properties
  application:
    name: controle-veiculo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}
resilience4j:
  circuitbreaker:
    instances:
      cotacaoCB:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        record-exceptions:
          - java.lang.Exception
      cotacaoFallbackCB:
        sliding-window-size: 3
        failure-rate-threshold: 100
        wait-duration-in-open-state: 10s
        record-exceptions:
          - java.lang.Exception
